excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ifreelander.github.io
title: ifreelander 
tagline: Work and Study notes
description: My awesome new site
paginate: 50

theme: jekyll-theme-hacker